env:
  MANIFEST: https://github.com/Evolution-X/manifest.git
  MANIFEST_BRANCH: tiramisu
  DEVICE: lmi
  OEM: xiaomi
  DT_LINK: https://github.com/ZenkaBestia/device_xiaomi_lmi.git -b 13-evox
  DT_PATH: device/$OEM/$DEVICE
  VT_LINK: https://github.com/ProjectElixir-Devices/vendor_xiaomi_lmi.git -b Tiramisu
  VT_PATH: vendor/$OEM/$DEVICE
  KT_LINK: https://github.com/ProjectElixir-Devices/kernel_xiaomi_lmi.git -b zen_plus-13
  KT_PATH: kernel/$OEM/$DEVICE
  LUNCH_COMBO: evolution_lmi-user
  TARGET: evolution
  OUTPUT: evolution*.zip

  # Not Recommended to Change
  SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
  CCACHE_SIZE: 30G
  CCACHE_DIR: $HOME/work/.ccache
  J_VAL: 16

  # Cirrus Specific Vars (Do *NOT* Change)
  CIRRUS_SHELL: bash

task:
  name: "LMI Evolution-X Build"
  timeout_in: 4h
  container:
    image: apon77/aosp:cirrus
    cpu: 8
    memory: 32G

  Storage_Checker:
    - df -h
    - lsblk
    - ls -l -a -h

  Sync_script:
    - bash sync.sh

  Build_script:
    - bash build.sh

  Upload_script:
    - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
    - bash upload.sh
